--Bloque plsql para realizar pruebas

SET SERVEROUTPUT ON;

DECLARE
V_ID NUMBER;
V_ID_SAL NUMBER;
V_DESCRIPCION VARCHAR2(20);
BEGIN
V_ID := 8;
V_ID_SAL :=0;
V_DESCRIPCION := 'X';
--SP_BUSCAR_SERVICIO_EXTRA(V_ID, V_ID_SAL, V_DESCRIPCION);
--SP_CREAR_SERVICIO_EXTRA(V_ID, V_DESCRIPCION);
--SP_MODIFICAR_SERVICIO_EXTRA(V_ID, V_DESCRIPCION);
--SP_ELIMINAR_SERVICIO_EXTRA(V_ID);
DBMS_OUTPUT.PUT_LINE('EL ID CAMBIADO FUE '|| V_ID_SAL || ' ' || v_descripcion);
END;