--Bloque plsql para realizar pruebas

SET SERVEROUTPUT ON;

DECLARE
V_ID NUMBER;
V_DESCRIPCION VARCHAR2(20);
BEGIN
V_ID := 1;
V_DESCRIPCION := 'X';
SP_ELIMINAR_SERVICIO_EXTRA(V_ID, V_DESCRIPCION);
DBMS_OUTPUT.PUT_LINE('EL ID CAMBIADO FUE '|| V_ID);
END;