--Bloque plsql para realizar pruebas
---------------------------------------------
-- BLOQUE PRUEBAS SERVICIO EXTRA
---------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
V_ID NUMBER;
V_ID_SAL NUMBER;
V_DESCRIPCION VARCHAR2(20);
BEGIN
V_ID := 8;
V_ID_SAL :=0;
V_DESCRIPCION := 'X';
--SP_BUSCAR_SERVICIO_EXTRA(V_ID, V_ID_SAL, V_DESCRIPCION);
--SP_CREAR_SERVICIO_EXTRA(V_ID, V_DESCRIPCION);
--SP_MODIFICAR_SERVICIO_EXTRA(V_ID, V_DESCRIPCION);
--SP_ELIMINAR_SERVICIO_EXTRA(V_ID);
DBMS_OUTPUT.PUT_LINE('EL ID CAMBIADO FUE '|| V_ID_SAL || ' ' || v_descripcion);
END;

---------------------------------------------
-- BLOQUE PRUEBAS DEPARTAMENTO
---------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
V_ID  NUMBER;
V_ID_SALIDA  NUMBER; 
V_DIRECCION  VARCHAR2(60);
V_NUMERO  NUMBER;
V_PRECIO  NUMBER;
V_M_CUADRADOS  VARCHAR2(20);
V_BANIOS  NUMBER;
V_DESCRIPCION  VARCHAR2(500);
V_CANTIDAD_HABITACION  NUMBER;
V_ID_ESTADO  NUMBER;
V_ID_REGION  NUMBER;
V_ID_COMUNA  NUMBER;
V_ID_INVENTARIO  NUMBER;
V_ID_FUNCIONARIO  NUMBER;
V_ID_SERVICIOS_EXTRA  NUMBER;
BEGIN
V_ID := 0;
V_ID_SALIDA := 0;
V_DIRECCION := 'DIR FALSA 123';
V_NUMERO := 0;
V_PRECIO := 0;
V_M_CUADRADOS := '0 MT2';
V_BANIOS := 0;
V_DESCRIPCION := 'DESC PIOLA';
V_CANTIDAD_HABITACION := 0;
V_ID_ESTADO := 0;
V_ID_REGION := 0;
V_ID_COMUNA := 0;
V_ID_INVENTARIO := 0;
V_ID_FUNCIONARIO := 0;
V_ID_SERVICIOS_EXTRA := 0;

--SP_BUSCAR_DEPARTAMENTO(V_ID, V_ID_SALIDA);
/*
SP_CREAR_DEPARTAMENTO(V_ID,
 V_DIRECCION,
 V_NUMERO,
 V_PRECIO,
 V_M_CUADRADOS,
 V_BANIOS,
 V_DESCRIPCION,
 V_CANTIDAD_HABITACION,
 V_ID_ESTADO,
 V_ID_REGION,
 V_ID_COMUNA,
 V_ID_INVENTARIO,
 V_ID_FUNCIONARIO,
 V_ID_SERVICIOS_EXTRA);
 */
/*
SP_MODIFICAR_DEPARTAMENTO(V_ID,
 V_DIRECCION,
 V_NUMERO,
 V_PRECIO,
 V_M_CUADRADOS,
 V_BANIOS,
 V_DESCRIPCION,
 V_CANTIDAD_HABITACION,
 V_ID_ESTADO,
 V_ID_REGION,
 V_ID_COMUNA,
 V_ID_INVENTARIO,
 V_ID_FUNCIONARIO,
 V_ID_SERVICIOS_EXTRA);
 */

--SP_ELIMINAR_DEPARTAMENTO(V_ID);
DBMS_OUTPUT.PUT_LINE('DATOS DEPARTAMENTO');
DBMS_OUTPUT.PUT_LINE('ID = ' || V_ID);
DBMS_OUTPUT.PUT_LINE('ID_SALIDA = ' || V_ID_SALIDA);
DBMS_OUTPUT.PUT_LINE('DIRECCION = ' || V_DIRECCION);
DBMS_OUTPUT.PUT_LINE('NUMERO = ' || V_NUMERO);
DBMS_OUTPUT.PUT_LINE('PRECIO = ' || V_PRECIO);
DBMS_OUTPUT.PUT_LINE('M_CUADRADOS = ' || V_M_CUADRADOS);
DBMS_OUTPUT.PUT_LINE('BANIOS = ' || V_BANIOS);
DBMS_OUTPUT.PUT_LINE('DESCRIPCION = ' || V_DESCRIPCION);
DBMS_OUTPUT.PUT_LINE('CANTIDAD_HABITACION = ' || V_CANTIDAD_HABITACION);
DBMS_OUTPUT.PUT_LINE('ID_ESTADO = ' || V_ID_ESTADO);
DBMS_OUTPUT.PUT_LINE('ID_REGION = ' || V_ID_REGION);
DBMS_OUTPUT.PUT_LINE('ID_COMUNA = ' || V_ID_COMUNA);
DBMS_OUTPUT.PUT_LINE('ID_INVENTARIO = ' || V_ID_INVENTARIO);
DBMS_OUTPUT.PUT_LINE('ID_FUNCIONARIO = ' || V_ID_FUNCIONARIO);
DBMS_OUTPUT.PUT_LINE('ID_SERVICIOS_EXTRA = ' || V_ID_SERVICIOS_EXTRA);
END;


---------------------------------------------
-- BLOQUE PRUEBAS CLIENTE
---------------------------------------------
SET SERVEROUTPUT ON;

DECLARE
V_ID  NUMBER;
V_ID_SALIDA  NUMBER; 
V_RUT  VARCHAR2(10);
V_NOMBRE  VARCHAR2(20);
V_PRIMER_APE  VARCHAR2(40);
V_SEGUNDO_APE  VARCHAR2(40);
V_DIRECCION  VARCHAR2(60);
V_TELEFONO  VARCHAR2(15);
V_FECHA_NAC  DATE;
V_CORREO  VARCHAR2(30);
V_FRECUENTE  NUMBER;
V_ID_COMUNA  NUMBER;
V_ID_REGION  NUMBER;
V_ID_NACIONALIDAD  NUMBER;

BEGIN
V_ID := 0;
V_ID_SALIDA := -1;
V_RUT := 'SIN RUT';
V_NOMBRE := 'SIN NAME';
V_PRIMER_APE := 'SIN APE';
V_SEGUNDO_APE := 'SIN APE';
V_DIRECCION := 'SIN DIRE';
V_TELEFONO := 'SIN FONO';
V_FECHA_NAC := '01/01/2020';
V_CORREO := 'SIN CORREO';
V_FRECUENTE := 0;
V_ID_COMUNA := 0;
V_ID_REGION := 0;
V_ID_NACIONALIDAD := 0;


--SP_BUSCAR_CLIENTE(V_ID, V_ID_SALIDA);
/*
SP_CREAR_CLIENTE(V_ID,
 V_RUT,
 V_NOMBRE,
 V_PRIMER_APE,
 V_SEGUNDO_APE,
 V_DIRECCION,
 V_TELEFONO,
 V_FECHA_NAC,
 V_CORREO,
 V_FRECUENTE,
 V_ID_COMUNA,
 V_ID_REGION,
 V_ID_NACIONALIDAD
 );
 */
/*
SP_MODIFICAR_CLIENTE(V_ID,
 V_RUT,
 V_NOMBRE,
 V_PRIMER_APE,
 V_SEGUNDO_APE,
 V_DIRECCION,
 V_TELEFONO,
 V_FECHA_NAC,
 V_CORREO,
 V_FRECUENTE,
 V_ID_COMUNA,
 V_ID_REGION,
 V_ID_NACIONALIDAD
 );
 */

--SP_ELIMINAR_CLIENTE(V_ID);
DBMS_OUTPUT.PUT_LINE('DATOS DEPARTAMENTO');
DBMS_OUTPUT.PUT_LINE('ID = ' || V_ID);
DBMS_OUTPUT.PUT_LINE('ID_SALIDA = ' || V_ID_SALIDA);
DBMS_OUTPUT.PUT_LINE('RUT = ' || V_RUT);
DBMS_OUTPUT.PUT_LINE('NOMBRE = ' || V_NOMBRE);
DBMS_OUTPUT.PUT_LINE('PRIMER_APE = ' || V_PRIMER_APE);
DBMS_OUTPUT.PUT_LINE('SEGUNDO_APE = ' || V_SEGUNDO_APE);
DBMS_OUTPUT.PUT_LINE('DIRECCION = ' || V_DIRECCION);
DBMS_OUTPUT.PUT_LINE('TELEFONO = ' || V_TELEFONO);
DBMS_OUTPUT.PUT_LINE('FECHA_NAC = ' || V_FECHA_NAC);
DBMS_OUTPUT.PUT_LINE('CORREO = ' || V_CORREO);
DBMS_OUTPUT.PUT_LINE('FRECUENTE = ' || V_FRECUENTE);
DBMS_OUTPUT.PUT_LINE('ID_COMUNA = ' || V_ID_COMUNA);
DBMS_OUTPUT.PUT_LINE('ID_REGION = ' || V_ID_REGION);
DBMS_OUTPUT.PUT_LINE('ID_NACIONALIDAD = ' || V_ID_NACIONALIDAD);

END;