---------------------------------------------
-- Procedimiento Crear servicio extra
---------------------------------------------
CREATE OR REPLACE PROCEDURE SP_CREAR_SERVICIO_EXTRA 
(P_ID IN NUMBER, 
P_DESCRIPCION IN VARCHAR2, 
P_AFFECTED OUT NUMBER) AS
BEGIN
    INSERT INTO SERVICIOS_EXTRA VALUES (P_ID,P_DESCRIPCION);
    P_AFFECTED := SQL%ROWCOUNT;
    COMMIT; -- PARA GUARDAR CAMBIO
EXCEPTION
    WHEN OTHERS THEN
        P_AFFECTED := 0;
END SP_CREAR_SERVICIO_EXTRA;

---------------------------------------------
-- Procedimiento Eliminar servicio extra
---------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_SERVICIO_EXTRA 
  (P_ID IN  NUMBER,
   P_AFFECTED OUT NUMBER) AS
BEGIN
  DELETE FROM SERVICIOS_EXTRA WHERE ID_SERVICIOS_EXTRA = P_ID;
  P_AFFECTED := SQL%ROWCOUNT;
  COMMIT; -- PARA GUARDAR CAMBIOS
EXCEPTION
  WHEN OTHERS THEN
    P_AFFECTED := 0;
END SP_ELIMINAR_SERVICIO_EXTRA;

---------------------------------------------
-- Procedimiento Modificar servicio extra
---------------------------------------------
CREATE OR REPLACE PROCEDURE SP_MODIFICAR_SERVICIO_EXTRA 
  (P_ID IN  NUMBER,
  P_DESCRIPCION IN VARCHAR2,
  P_AFFECTED OUT NUMBER) AS
BEGIN
  UPDATE SERVICIOS_EXTRA
  SET DESCRIPCION = P_DESCRIPCION
  WHERE ID_SERVICIOS_EXTRA = P_ID;
  P_AFFECTED := SQL%ROWCOUNT;
  COMMIT; -- PARA GUARDAR CAMBIOS 
EXCEPTION
  WHEN OTHERS THEN
    P_AFFECTED := 0;
END SP_MODIFICAR_SERVICIO_EXTRA;
