---------------------------------------------
-- Procedimiento Crear servicio extra
---------------------------------------------
CREATE OR REPLACE PROCEDURE SP_CREAR_SERVICIO_EXTRA 
(P_DESCRIPCION IN VARCHAR2, 
P_PRECIO IN NUMBER,
P_AFFECTED OUT NUMBER) AS
BEGIN
    INSERT INTO SERVICIO_EXTRA VALUES (SERVICIO_EXTRA_ID_SEQ.NEXTVAL,P_DESCRIPCION, 1, P_PRECIO);
    P_AFFECTED := SQL%ROWCOUNT;
    COMMIT; -- PARA GUARDAR CAMBIO
EXCEPTION
    WHEN OTHERS THEN
        P_AFFECTED := 0;
END SP_CREAR_SERVICIO_EXTRA;

---------------------------------------------
-- Procedimiento Eliminar servicio extra
---------------------------------------------
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_SERVICIO_EXTRA 
  (P_ID IN  NUMBER,
   P_AFFECTED OUT NUMBER) AS
BEGIN
  DELETE FROM SERVICIO_EXTRA WHERE ID_SERVEXTRA = P_ID;
  P_AFFECTED := SQL%ROWCOUNT;
  COMMIT; -- PARA GUARDAR CAMBIOS
EXCEPTION
  WHEN OTHERS THEN
    P_AFFECTED := 0;
END SP_ELIMINAR_SERVICIO_EXTRA;

---------------------------------------------
-- Procedimiento Modificar servicio extra
---------------------------------------------
CREATE OR REPLACE PROCEDURE SP_MODIFICAR_SERVICIO_EXTRA 
  (P_ID IN  NUMBER,
  P_DESCRIPCION IN VARCHAR2,
  P_PRECIO IN NUMBER,
  P_AFFECTED OUT NUMBER) AS
BEGIN
  UPDATE SERVICIO_EXTRA
  SET DESC_SERV = P_DESCRIPCION,
      PRECIO = P_PRECIO
  WHERE ID_SERVEXTRA = P_ID;
  P_AFFECTED := SQL%ROWCOUNT;
  COMMIT; -- PARA GUARDAR CAMBIOS 
EXCEPTION
  WHEN OTHERS THEN
    P_AFFECTED := 0;
END SP_MODIFICAR_SERVICIO_EXTRA;
